apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra
  namespace: spark-cluster
spec:
  #  type: NodePort
  clusterIP: None
  ports:
    - port: 9042
#      nodePort: 30082
  selector:
    app: cassandra
